syntax = "All"
column_width = 180
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "FunctionOnly"
collapse_simple_statement = "Always"
space_after_function_names = "Never"

[sort_requires]
enabled = false
