tab_spaces = 2
max_width = 120
chain_width = 100
comment_width = 100
struct_lit_width = 100
fn_args_layout = "Compressed"

imports_layout = "Vertical"
imports_granularity = "Crate"

wrap_comments = true
format_strings = true
format_code_in_doc_comments = true
