#  ███████╗███████╗███████╗██╗  ██╗
#  ██╔════╝██╔════╝██╔════╝██║  ██║
#  ███████╗█████╗  ███████╗███████║
#  ╚════██║██╔══╝  ╚════██║██╔══██║
#  ███████║███████╗███████║██║  ██║
#  ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
#  Smart session manager for the terminal
#  https://github.com/joshmedeski/sesh

blacklist = ["scratch"]

# default

[default_session]
startup_command = "nvim"
startup_command_ignore_dirs = ["~/repos", "~/.config"]
preview_command = "eza --all --git --icons --color=always {}"

# common
[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "repositories (c)"
path = "~/Repository"
startup_command = "ls"

[[session]]
name = "Home (~)"
path = "~"
startup_command = "ls"


# configs

[[session]]
name = "dotfiles"
path = "~/Repository/dotfiles"

[[session]]
name = "nvim config"
path = "~/Repository/dotfiles/.config/nvim"

[[session]]
name = "tmux config"
path = "~/Repository/dotfiles/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --language=bash --style=snip --color=always ~/c/dotfiles/.config/tmux/tmux.conf"
