
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

command_timeout = 2000

format = """$username$hostname$directory$fill(grey) $time$line_break$character"""

[character]
success_symbol = "[\uf054](bold green)"
error_symbol = "[\uf054](bold red)"

[fill]
symbol = '─'

[time]
disabled = false
time_format = "%F %T"
style = "#444444"
format = '[$time]($style)'
